SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

CREATE SCHEMA IF NOT EXISTS `InternetBanking` DEFAULT CHARACTER SET utf8 COLLATE utf8_czech_ci ;

USE `InternetBanking`;

CREATE  TABLE IF NOT EXISTS `InternetBanking`.`Bank` (
  `code` INT(11) NOT NULL ,
  `Bankcol` VARCHAR(255) NOT NULL ,
  PRIMARY KEY (`code`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_czech_ci;

CREATE  TABLE IF NOT EXISTS `InternetBanking`.`Currency` (
  `code` VARCHAR(3) NOT NULL ,
  `name` VARCHAR(45) NOT NULL ,
  `decimalDigits` INT(11) NOT NULL ,
  PRIMARY KEY (`code`) ,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_czech_ci;

CREATE  TABLE IF NOT EXISTS `InternetBanking`.`Customer` (
  `id` INT(11) NOT NULL ,
  `firstName` VARCHAR(250) NOT NULL ,
  `Customercol` VARCHAR(250) NOT NULL ,
  `email` VARCHAR(500) NOT NULL ,
  PRIMARY KEY (`id`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_czech_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
